spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: spcoff@naver.com
    password: dhtjdals88@@
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  mvc:
    view:
      prefix: /name
  #      suffix: .html
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/sma
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: update
      #ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20
  batch:
    jdbc:
      initialize-schema: always
logging.level:
  org.hibernate.SQL: debug

  server:
    error:
      path: /error



